apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/will-moz/soupy-sales:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/will-moz/soupy-sales:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: soupy-sales
        chartPath: charts/soupy-sales
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/will-moz/soupy-sales"
          image.tag: "{{.DIGEST_HEX}}"
